server:
  port: 8763
spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          username: ''
          password: ''
          searchPaths: /**
          uri: https://github.com/lihao80/spring-cloud-config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

